# Generated by Django 3.1 on 2021-06-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'produit', 'verbose_name_plural': 'produits'},
        ),
    ]
