# Generated by Django 3.1 on 2021-06-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210625_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles dans le panier'},
        ),
    ]
