# Generated by Django 3.1 on 2021-06-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'commande'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'produit commandé', 'verbose_name_plural': 'produits commandés'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payement'},
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(max_length=100, verbose_name='Montant à payer'),
        ),
    ]
